---
services:
  build:
    build:
      context: ..
      dockerfile: docker/build.Dockerfile
    volumes:
      - ../dist:/service/dist:consistent
      - ../types:/service/types:consistent
  postgres:
    build:
      context: ..
      dockerfile: docker/postgres.Dockerfile
    environment:
      - "POSTGRES_DB=test"
      - "POSTGRES_PASSWORD=test"
      - "POSTGRES_USER=test"
    ports:
      - "5432:5432"
  test:
    build:
      context: ..
      dockerfile: docker/test.Dockerfile
    depends_on:
    - postgres
    links:
    - postgres
    volumes:
      - ../tsconfig.json:/service/tsconfig.json:cached
      - ../src:/service/src:cached
